spring.application.name=biblioteca
# Configuração do MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/biblioteca_pessoal

# Desabilitar segurança momentaneamente (apenas para testar o CRUD inicial)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Mostrar logs do MongoDB (útil para debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# URL da API Google Books (pode ser WireMock ou real)
api.google-books.url=https://www.googleapis.com/books/v1
