spring.application.name=biblioteca
# Configuração do MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/biblioteca_pessoal

# Mostrar logs do MongoDB (útil para debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# URL da API Google Books (pode ser WireMock ou real)
api.google-books.url=https://www.googleapis.com/books/v1
# Opcional: chave da Google Books API (evita erro 429 por cota compartilhada)
api.google-books.api-key=AIzaSyBOsSW2ZTMSNisVHfAiiJSoyxTlCMTTN-Y
api.viacep.url=https://viacep.com.br/ws
app.admin.default-password=AdminSenha123